services:
  gas-template:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gas-template
    hostname: gas-template
    shm_size: '4gb'
    volumes:
      - ./:/workspace:cached
    environment:
      GIT_AUTHOR_NAME: ${GIT_USERNAME}
      GIT_COMMITTER_NAME: ${GIT_USERNAME}
      GIT_AUTHOR_EMAIL: ${GIT_EMAIL_ADDRESS}
      GIT_COMMITTER_EMAIL: ${GIT_EMAIL_ADDRESS}
      TZ: Asia/Tokyo
    tty: true
